(()=>{
const $=s=>document.querySelector(s);const media=matchMedia('(prefers-reduced-motion: reduce)');let manual=false;const reduced=()=>manual||media.matches;
const animations=new Set(),inkRuns=new Map();
function animate(el,frames,options){if(!el||reduced())return;const a=el.animate(frames,options);animations.add(a);a.onfinish=a.oncancel=()=>animations.delete(a)}
function applyPreference(){document.documentElement.classList.toggle('reduced-motion',reduced());$('#motion-toggle').setAttribute('aria-pressed',String(reduced()));$('#motion-toggle').setAttribute('aria-label',media.matches?'Movimento reduzido pelo sistema':'Reduzir movimento');if(reduced()){for(const a of animations)a.cancel();for(const stop of inkRuns.values())stop()}}
$('#motion-toggle').addEventListener('click',()=>{manual=!manual;applyPreference()});media.addEventListener('change',applyPreference);applyPreference();
const menu=$('#mobile-menu'),toggle=$('.menu-toggle');toggle.addEventListener('click',()=>{menu.showModal();toggle.setAttribute('aria-expanded','true')});$('#menu-close').addEventListener('click',()=>menu.close());menu.addEventListener('close',()=>{toggle.setAttribute('aria-expanded','false');toggle.focus()});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu.close()));
const dialog=$('#photo-dialog');let opener;document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{opener=b;$('#photo-large').src=b.dataset.photo;$('#photo-large').alt=b.dataset.caption;$('#photo-caption').textContent=b.dataset.caption;dialog.showModal()}));$('#photo-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>opener?.focus());
const tabs=[...document.querySelectorAll('[role=tab]')];function select(tab,moveFocus=false){tabs.forEach(t=>{const on=t===tab;t.setAttribute('aria-selected',String(on));t.tabIndex=on?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=!on});if(moveFocus)tab.focus();animate(document.getElementById(tab.getAttribute('aria-controls')).querySelector('.practice-content'),[{opacity:.35,transform:'translateY(6px)'},{opacity:1,transform:'translateY(0)'}],{duration:380,easing:'cubic-bezier(.18,.8,.2,1)'})}
tabs.forEach((t,i)=>{t.addEventListener('click',()=>select(t));t.addEventListener('keydown',e=>{let n;if(['ArrowRight','ArrowDown'].includes(e.key))n=(i+1)%tabs.length;if(['ArrowLeft','ArrowUp'].includes(e.key))n=(i+tabs.length-1)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();select(tabs[n],true)}})});if(tabs.length)select(tabs[0]);
// A feathered mask reveals existing ink artwork; no photograph is altered.
async function reveal(el){if(reduced())return;const image=new Image();image.src=el.dataset.ink;try{await image.decode()}catch{return}if(reduced()||!el.isConnected)return;const r=el.getBoundingClientRect();const w=Math.min(640,Math.round(r.width*1.25)),h=Math.round(w*r.height/r.width);if(!w||!h)return;const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.className='ink-canvas';canvas.setAttribute('aria-hidden','true');const ctx=canvas.getContext('2d');const mask=document.createElement('canvas');mask.width=w;mask.height=h;const m=mask.getContext('2d');if(!ctx||!m)return;let frame;const stop=()=>{cancelAnimationFrame(frame);canvas.remove();el.classList.remove('ink-active');inkRuns.delete(el)};inkRuns.set(el,stop);el.append(canvas);el.classList.add('ink-active');const scale=Math.min(w/image.width,h/image.height),iw=image.width*scale,ih=image.height*scale,start=performance.now();function draw(now){if(reduced()||document.hidden){stop();return}const t=Math.min(1,(now-start)/1400),p=1-Math.pow(1-t,2.2);m.clearRect(0,0,w,h);m.fillStyle='#000';m.filter='blur(4px)';m.beginPath();m.moveTo(0,0);m.lineTo(w,0);for(let x=w;x>=0;x-=4)m.lineTo(x,(-.15+1.4*p)*h+Math.sin(x/w*19)*h*.025+Math.sin(x/w*51)*h*.009);m.lineTo(0,0);m.fill();ctx.clearRect(0,0,w,h);ctx.globalCompositeOperation='source-over';ctx.drawImage(image,(w-iw)/2,(h-ih)/2,iw,ih);ctx.globalCompositeOperation='destination-in';ctx.drawImage(mask,0,0);if(t<1)frame=requestAnimationFrame(draw);else stop()}frame=requestAnimationFrame(draw)}
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){observer.unobserve(e.target);reveal(e.target)}}),{threshold:.3});document.querySelectorAll('[data-ink]').forEach(el=>observer.observe(el));
addEventListener('resize',()=>{for(const stop of inkRuns.values())stop();if(innerWidth>800&&menu.open)menu.close()});document.addEventListener('visibilitychange',()=>{if(document.hidden){for(const stop of inkRuns.values())stop();for(const a of animations)a.cancel()}});
})();
